Refresh jwt on every request
KIT-PSE/collab-space-backend pull request #20
Opened 2023-07-09 18:16 UTC by mariusfriess

resolves https://github.com/KIT-PSE/collab-space-app/issues/6

Habe nen neuen PR geöffnet, da ich von vorne angefangen habe und nix aus dem Code den ich da zuvor mal hatte gebraucht wird.

Habe hier jetzt einfach den AuthGuard genutzt und dort die Aktualisierung des Tokens implementiert.

2023-07-13 17:09 UTC, mariusfriess commented
Wie sieht's hiermit aus? Anmerkungen oder mergen?

2023-07-14 21:05 UTC, FlorianRaith requested changes

2023-07-14 21:05 UTC, FlorianRaith commented on src/auth/auth.guard.ts
> +    const _canActivate = (await super.canActivate(context)) as boolean;
keine Unterstriche in Variabel Namen

2023-07-17 12:53 UTC, FlorianRaith approved these changes

2023-07-17 12:54 UTC, merged